services:

  ui:
    image: localhost/soi24/ui:1
    restart: always
    ports:
      - "80:80"

  web-server:
    image: localhost/soi24/web-server:1
    restart: always
    #ports:
    #  - "8080:8080"
    deploy:
      replicas: 2

  redis:
    image: redis:7.2
    restart: always
    #ports:
    #  - "6379:6379"
    volumes:
      - redis-data:/data

  stomp-relay:
    image: rabbitmq:3.12
    restart: always
    #ports:
    #  - "61613:61613"
    command: [
      "/bin/sh", "-c",
      "rabbitmq-plugins enable --offline rabbitmq_stomp && exec rabbitmq-server"
    ]
    volumes:
      - stomp-relay-data:/var/lib/rabbitmq

volumes:
  redis-data:
  stomp-relay-data:
